### PR TITLE
Added support for Ubuntu and CentOS

### PR DESCRIPTION
**Pull request by kupferk**
As your module works fine with Ubuntu (at least 14.04), I added the corresponding cases. I also added CentOS, this should also work.

### CODE REVIEW

**Comment by valtri** [comment]
Great it works also on Ubuntu, thanks for testing! Do you use it with Cloudera distribution?

The CentOS should be probably tested before announcing its support. I would expect problems, because there is used just 'RedHat' in some conditionals and there could be some differencies between native packaging in Fedora and Cloudera on CentOS.

**Comment by valtri** [comment]
Btw. the newest puppet documentation recommends to remove Modulefile from modules. Is it needed? (Probably for some older version of puppet? This module requires puppet >= 3 though.)

**Comment by kupferk** [comment]
Thanks for you remarks. 

Yes, I am using the Cloudera distribution on Ubuntu 14.04, together with the puppet module razorsedge/cloudera which takes care of setting up the correct repositories.

You are right, CentOS should be tested, but actually I didn't include CentOS in the metadata.json yet. So this would be a first step into the direction of fully supporting CentOS.

Regarding the Modulefile, you are absolutely correct. Unfortunately Ubuntu 14.04 still ships with puppet 3.4.x which doesn't seem to support the new metadata.json for building Puppet modules. So I added the Modulefile - but maybe I am missing something here and there is some way to get puppet 3.4.x working with the new metadata.json.

**Comment by valtri** [comment]
Thanks! Applied.

**Pull request merged**
